### PR TITLE
add french locales, correct a bit of the english ones

### PR DESCRIPTION
**Pull request by Bumbadawg**

### CODE REVIEW

**Comment by gdh1995** [comment]
Thanks a lot!

Here's some of my questions:

you know, `Vimium C - All by keyboard` was the full name of this extension,
1. `Everything by the keyboard` looks (just a bit) too long to show and read;
2. Is the word `the` necessary? Maybe we can drop it since all people can understand the whole name without it.

Some placeholders like `$1`, `$2` and `$3`, have special formats
* for example, in `markRemoved`'s `"$1 $2 mark$3 been removed."`, `$1` is the number, `$2` is `trans("local")` or `trans("global")`, and `$3` is `trans("have")` or `trans("has")`
* as you can see, `trans("have")` returns `"s have"`, which means plural forms
* So in the current commit the modification is somehow not what I wanted to represent

To get the meanings of placeholders like `$1`, you may search the name of a message item in TypeScript/HTML files. For example, when you search `markRemoved`, you'll find:
https://github.com/gdh1995/vimium-c/blob/be9e6d26f90e01199d947ac9b840cf8c7198a78d/background/tools.ts#L433-L435

* `trans_`, `pTrans_` and `VTr` are the translating functions, and their logic are similar
* the first function argument is the name to find translation messages
* the second argument, if exists, is a list of dynamic text, and will replace `$1`, `$2`, `$3` and so on.

**Comment by Bumbadawg** [comment]
Thank you for hitting back a response so fast!

 > you know, `Vimium C - All by keyboard` was the full name of this extension

Oops, pardon the cavalier commit :-1:
First off, like you say, people will get it, no need to modify this.
We'd require a native speaker to confirm the following because like you, i'm not english-native neither. Here is how i grammatically interpret it:
* _"all by oneself / one thing"_ means _"alone with oneself / one thing (keyboard here)"_, which could convey a negative perception.
* _"only with"_ is what you're trying to imply, thus the _"everything by"_.
_"the"_ sure can be dropped :-)

> as you can see, trans("have") returns "s have", which means plural forms

Indeed, and i messed up your formatting, thinking the missing space between `mark` and `$3` was a typo for instance, how presumptuous..
The future commit will take into account your trans() functions to better match the contextual meaning.

Finally, i sometimes removed the ending dot `.` to some messages. Thinking it was a typo as well. Are those ending dots mandatory to messages ?

**Comment by gdh1995** [comment]
Then we may use "everything by keyboard".


You may use and add placeholders as you like, only if some sentences need to be splitted in French/English.


Dot can be removed totally, except one in the "copied: *** ." tip.



---Original---

**Comment by gdh1995** [comment]
(Um, in the last commit I added a paragraph):
https://github.com/gdh1995/vimium-c/blob/d1b4d81ddd96ffa0bc912d26b5a0fa21322e8559/pages/popup.html#L119-L123 .

**Comment by gdh1995** [comment]
Here's a new question:

on Chrome Web Store, it show extension names in page URLs, so the old URL of Vimium C is 
https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg ;
while for v1.81.4 the URL is 
https://chrome.google.com/webstore/detail/vimium-c-everything-by-ke/hfjbmagddngcpeloejdejnfgbamkjaeg .

As you can see, the word of `keyboard` is truncated. I want to find a better solution but unfortunately there seem no more suitable words ...

**Comment by gdh1995** [comment]
I've merged this PR in eeb3d84641bdb6c9ed73d3252f79814f8ae062a0, to modify it like what I've said above. So if you have any new ideas, fell free to say it here or file a new issue/PR.

**Comment by gdh1995** [comment]
Hello, I've decided to change license of all the translation files (those in the [_locales/](https://github.com/gdh1995/vimium-c/tree/master/_locales) folder) to [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/).

If you disagree it, please tell me here in this month and I'll add special declarations for your translation in French.

**Pull request closed without merging**
