### PR TITLE
fix skipping minimized window on `moveTabToNextWindow` command

### PR DESCRIPTION
**Pull request by fent**
I noticed it unminimized one of my windows when moving a tab, so added a check for minimized to the filter

### CODE REVIEW

**Comment by gdh1995** [comment]
How about adding an command option to toggle this filter?

**Comment by fent** [comment]
command option? hmm I'll have to figure out how to do that

**Comment by gdh1995** [comment]
I've pushed commit 3e5d4016f7fb819a506e01de79af3d96c3c12f44 to add this command option:

https://github.com/gdh1995/vimium-c/blob/3e5d4016f7fb819a506e01de79af3d96c3c12f44/background/main.ts#L1548-L1550

**Comment by gdh1995** [comment]
Hello, v1.85,1 has been released, and it has merged this.

**Pull request merged**
